M48
; DRILL file {KiCad 9.0.0} date 2025-08-11T15:21:15+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-11T15:21:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.4528Y-3.2768
X3.4528Y-4.6768
X4.3528Y-3.2768
X4.3528Y-4.6768
M30
